name: Release

on:
  push:
    tags:
    - 'v*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.16
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Get dependencies
      run: |
        go get -v -t ./...

    - name: Build
      run: |
        ./build.sh build

    - run: |
        set -x
        tag_name="${GITHUB_REF##*/}"
        gh release create "$tag_name" build/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
